package com.igorgrabarski;

/**
 * Created by igorgrabarski on 2017-06-09.
 */
public enum ItemType {
    MOVIE,
    MOVIE_POPULAR,
    MOVIE_TOP_RATED,
    MOVIE_NOW_PLAYING,
    MOVIE_UPCOMING,
    MOVIES_RECOMMENDED,
    MOVIES_SIMILAR,
    MOVIE_REVIEWS,
    MOVIE_VIDEOS,
    MOVIE_CREDITS,
    MOVIE_SEARCH,
    MOVIE_KEYWORDS,
    TV,
    TV_LATEST,
    TV_AIRING_TODAY,
    TV_ON_THE_AIR,
    TV_POPULAR,
    TV_TOP_RATED,
    TVS_SIMILAR,
    TVS_RECOMMENDED,
    TV_REVIEWS,
    TV_VIDEOS,
    TV_CREDITS,
    TV_SEARCH,
    TV_KEYWORDS,
    TV_SEASON,
    PERSON_SEARCH,
    MULTI_SEARCH,
    PERSON_DETAILS,
    PERSON_CREDITS_MOVIE,
    PERSON_CREDITS_TV,
    PERSON_CREDITS_COMBINED
}
